 **1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operation?**


**NumPy is a powerful Python library for numerical computing, widely used in scientific computing and data analysis due to its efficiency and functionality.** At its core, NumPy provides support for large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays.

**Purpose and Advantages:**

**Efficient Data Storage and Manipulation:** NumPy arrays (ndarrays) are more memory-efficient than Python lists, allowing for faster data processing, especially with large datasets.

**Mathematical Operations:** It enables fast and efficient mathematical operations on arrays, including element-wise operations and complex linear algebra, which are foundational in data analysis and scientific computing.

**Broad Functionality:** With functions for random number generation, statistical calculations, Fourier transforms, and more, NumPy is highly versatile for both basic and advanced mathematical tasks.

**Interoperability:** NumPy seamlessly integrates with other libraries, like Pandas, Matplotlib, and SciPy, enhancing Python's data manipulation and visualization capabilities, making it the backbone of the data science ecosystem.

**Vectorization:** Through vectorization (performing operations on entire arrays rather than element-by-element), NumPy enables faster, more readable code by minimizing the need for explicit loops, which is essential for performance optimization.

**2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?**



**In NumPy, np.mean() and np.average() both compute the average of array elements, but they differ in functionality: **

**np.mean() calculates the simple arithmetic mean of an array, treating all elements equally.
np.average() allows weighting of elements through a weights parameter. This means you can calculate a weighted average, where some elements contribute more than others to the final result.**

**When to Use Each:**

Use np.mean() when you need a straightforward average with all elements equally contributing.
Use np.average() when elements have varying importance (e.g., calculating a grade with different weights for exams and assignments).

**Example: For an array [1, 2, 3], np.mean() and np.average() both give 2.0 without weights. But with weights [1, 2, 1], np.average() would yield a weighted average of 2.25.**

**3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.**



**In NumPy, you can reverse an array along different axes using slicing and the np.flip() function. Here’s how these methods work with both 1D and 2D arrays:**

**1. Using Slicing ([::-1])**

1D Array: Reverse all elements with slicing.

In [1]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4])
reversed_1d = arr_1d[::-1]
print(reversed_1d)  # Output: [4, 3, 2, 1]

[4 3 2 1]


**2D Array: Reverse along rows or columns.**

In [2]:
arr_2d = np.array([[1, 2], [3, 4]])
reversed_rows = arr_2d[::-1]          # Reverse row order
reversed_columns = arr_2d[:, ::-1]    # Reverse column order
print(reversed_rows)     # Output: [[3, 4], [1, 2]]
print(reversed_columns)  # Output: [[2, 1], [4, 3]]

[[3 4]
 [1 2]]
[[2 1]
 [4 3]]


**2. Using np.flip()**

Slicing is quick and commonly used, but np.flip() adds clarity and flexibility for multidimensional arrays.

In [3]:
reversed_1d_flip = np.flip(arr_1d)
print(reversed_1d_flip)  # Output: [4, 3, 2, 1]

reversed_rows_flip = np.flip(arr_2d, axis=0)  # Reverse row order
reversed_columns_flip = np.flip(arr_2d, axis=1)  # Reverse column order
print(reversed_rows_flip)   # Output: [[3, 4], [1, 2]]
print(reversed_columns_flip) # Output: [[2, 1], [4, 3]]

[4 3 2 1]
[[3 4]
 [1 2]]
[[2 1]
 [4 3]]


**4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.**

**import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: dtype('int64')**

In [4]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: dtype('int64')

int64


**Importance of Data Types:**

**Memory Management:** Data types define how much memory each element consumes (e.g., int32 uses 4 bytes, float64 uses 8 bytes). Choosing the correct type helps minimize memory usage, especially with large datasets.

**Performance:** Operations on smaller data types are faster because they use less memory and processing power. For instance, using int16 instead of int64 when possible can speed up calculations.

In short, selecting appropriate data types in NumPy ensures efficient memory use and faster computations.

**5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**


In NumPy, an ndarray (N-dimensional array) is a powerful data structure for handling large, multi-dimensional data collections. It is the core of NumPy and allows for efficient storage and manipulation of arrays.

**Key Features of ndarrays:**
Fixed Size and Homogeneous Data: Elements in an ndarray are of a single data type, making memory usage more efficient.
Supports Vectorized Operations: Enables fast element-wise operations without loops, allowing calculations on entire arrays at once.

**N-dimensional:** Easily supports multi-dimensional data (e.g., 1D, 2D, or more), which is essential for complex datasets in scientific computing.

**Efficient Memory Use**: Stores data in contiguous blocks, leading to faster data access and processing.

**Difference from Python Lists:**

**Homogeneity:** Lists can store different data types, while ndarrays store only one, optimizing speed.

**Performance:** Ndarrays are faster and more memory-efficient than lists, especially with large data, due to optimized C-based implementations.
In short, ndarrays provide structured, fast, and efficient array handling, ideal for scientific computing.

**6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations?**


**NumPy arrays outperform Python lists in large-scale numerical operations due to:**


**Memory Efficiency: **NumPy arrays use fixed, contiguous memory blocks, unlike Python lists, which store elements as objects with extra metadata. This reduces memory overhead and enables efficient storage.

**Vectorized Operations**: NumPy allows operations on entire arrays at once (vectorization), eliminating slow Python loops. This boosts performance as operations are implemented in low-level C code, optimized for speed.

**Type Consistency:** NumPy arrays store elements of the same type, making calculations faster than with lists, which can store mixed types.

In summary, NumPy’s memory efficiency and vectorization make it ideal for fast, large-scale computations.

**7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output?**


In NumPy, vstack() and hstack() are used to stack arrays vertically and horizontally, respectively.

**1. np.vstack()** - Vertical Stacking
Stacks arrays row-wise (one on top of the other).
The arrays must have the same number of columns.

In [5]:
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.vstack((arr1, arr2))
print(result)

[[1 2]
 [3 4]]


**2. np.hstack() - Horizontal Stacking
Stacks arrays column-wise (side-by-side).
The arrays must have the same number of rows.?**

Summary: Use vstack() to add rows and hstack() to add columns, ensuring compatibility in shape (either rows or columns).

In [6]:
arr3 = np.array([[1], [2]])
arr4 = np.array([[3], [4]])
result = np.hstack((arr3, arr4))
print(result)

[[1 3]
 [2 4]]


**8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensionst?**

In NumPy, fliplr() and flipud() are used to flip arrays along different axes:

**1. np.fliplr()** - Flip Left to Right
Flips an array horizontally (left to right).
Applicable only to 2D or higher-dimensional arrays.

In [7]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
flipped_lr = np.fliplr(arr)
print(flipped_lr)

[[2 1]
 [4 3]]


**2. np.flipud()** - Flip Up to Down

Flips an array vertically (up to down).
Works on any array with 2 or more dimensions.

Summary: Use fliplr() to flip horizontally and flipud() to flip vertically. Both are useful for reorganizing data in matrices and images.

In [8]:
flipped_ud = np.flipud(arr)
print(flipped_ud)

[[3 4]
 [1 2]]


**9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

The array_split() method in NumPy splits an array into specified numbers of sub-arrays. Unlike split(), it can handle cases where the array cannot be divided evenly.

How It Handles Uneven Splits
If the array cannot be split evenly, array_split() makes the initial sub-arrays larger.
This ensures all parts have nearly equal elements, distributing the remainder to the first few sub-arrays.

Summary: array_split() is flexible for uneven divisions, making it ideal for dynamic data partitioning.

In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = np.array_split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5])]


**10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?**

**Vectorization and broadcasting are key concepts in NumPy that enhance performance by optimizing array operations:**

**1. Vectorization**
Vectorization allows operations to be applied directly on entire arrays instead of looping through individual elements.
It makes code faster and cleaner by offloading operations to optimized, low-level C functions.

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = 2          # Scalar broadcasted to array
result = arr1 + arr2  # Output: [3, 4, 5]

**2. Broadcasting**
Broadcasting allows arrays of different shapes to be combined in operations by “stretching” smaller arrays along specific dimensions without making extra copies.
Enables efficient operations between arrays without reshaping or replicating data.

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = 2          # Scalar broadcasted to array
result = arr1 + arr2  # Output: [3, 4, 5]

### **Practical Questions:**

**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns?**

In [12]:
import numpy as np

import random

ar=np.random.randint(1,100,size=(3,3))

print("Original Array",ar)

print("Interchanged Array",ar.T)

Original Array [[98 26 13]
 [99  9 71]
 [45 90 82]]
Interchanged Array [[98 99 45]
 [26  9 90]
 [13 71 82]]


**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array?**

In [13]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # Creates an array with elements from 0 to 9

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Display the results
print("1D Array:")
print(array_1d)

print("\nReshaped to 2x5 Array:")
print(array_2x5)

print("\nReshaped to 5x2 Array:")
print(array_5x2)

1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array?**

In [14]:
import numpy as np
import random

a4x4=np.random.rand(4,4)
print("Original Array\n",a4x4)

a6x6=np.pad(a4x4,pad_width=1,mode='constant',constant_values=0)
print("\nNew Array\n\n",a6x6)

Original Array
 [[0.55249434 0.28780929 0.58427296 0.65512125]
 [0.74246052 0.65557602 0.81385828 0.47669839]
 [0.30334917 0.04171984 0.36389859 0.89449212]
 [0.31961624 0.69365096 0.42648135 0.17051228]]

New Array

 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.55249434 0.28780929 0.58427296 0.65512125 0.        ]
 [0.         0.74246052 0.65557602 0.81385828 0.47669839 0.        ]
 [0.         0.30334917 0.04171984 0.36389859 0.89449212 0.        ]
 [0.         0.31961624 0.69365096 0.42648135 0.17051228 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4.Using NumPy, create an array of integers from 10 to 60 with a step of 5?**

In [15]:
array_of_integers = np.arange(10, 61, 5)
print(array_of_integers)

[10 15 20 25 30 35 40 45 50 55 60]


**5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element?**

In [16]:
array_of_strings = np.array(['python', 'numpy', 'pandas'])
print("Original Array",array_of_strings)

print(" \n\n upper case array :",np.char.upper(array_of_strings))

print(" \n\n lower case array :",np.char.lower(array_of_strings))

print(" \n\n title case array :",np.char.title(array_of_strings))

Original Array ['python' 'numpy' 'pandas']
 

 upper case array : ['PYTHON' 'NUMPY' 'PANDAS']
 

 lower case array : ['python' 'numpy' 'pandas']
 

 title case array : ['Python' 'Numpy' 'Pandas']


**6.Generate a NumPy array of words. Insert a space between each character of every word in the array?**

In [17]:
words=np.array(['python', 'numpy', 'pandas'])

spaced_words = np.char.join(' ', words)

print(spaced_words)

['p y t h o n' 'n u m p y' 'p a n d a s']


**7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division?**

In [18]:
a1=np.array([[1,2,3],[4,5,6]])

a1=a1*2
print(a1)

a2=np.array([[7,8,9],[10,11,12]])

a2=a2*2
print("\n\n",a2)


import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2         # Element-wise addition
subtraction = array1 - array2      # Element-wise subtraction
multiplication = array1 * array2   # Element-wise multiplication
division = array1 / array2         # Element-wise division

# Display the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)


[[ 2  4  6]
 [ 8 10 12]]


 [[14 16 18]
 [20 22 24]]
Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


**8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements?**

In [19]:
m = np.matrix(np.random.randint(1, 101, size=(5, 5)))
print(m,"\n\n")

d=np.diagonal(m)
print(d)

[[24 28 99 65  3]
 [26 64 74 44 16]
 [90 91 20 19 88]
 [58 75 70 13 78]
 [57 82 36 13 23]] 


[24 64 20 13 23]


**9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array?**

In [20]:
n=np.random.randint(0,1000,size=(100))
print(n,"\n\n")

def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    else:
      return True
prime_numbers = [num for num in n if is_prime(num)]

print("\n\n Prime numbers in the array:",prime_numbers)

[ 23  64 106 991 921 992 967 997 108 854  40 280  42 629 907 139 309 342
 398 134 850 228 372 404 778 959 246 562 115 991 127 897 484 275  99 311
 949 768 242 193 797 408 766 934 321 118 725   1 355 617 173  28 592 285
 339 198 503 803 121 996 697 842 434 639 155 998 151  59 533 664 656 268
 728 224 783 962 684 106 498 295 430 755 313 473 289 829 554 424 367 370
 776 482 641  81 499 782 724 258 363 442] 




 Prime numbers in the array: [23, 991, 967, 997, 629, 907, 139, 959, 115, 991, 127, 275, 311, 949, 193, 797, 725, 355, 617, 173, 503, 803, 121, 697, 155, 151, 59, 533, 295, 755, 313, 473, 289, 829, 367, 641, 499]


**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages?**

In [21]:
import numpy as np

# Generate a random array of daily temperatures for 30 days between 15°C and 35°C
daily_temperatures = np.random.randint(15, 36, size=30)
print("Daily Temperatures for the Month:\n", daily_temperatures)

# Reshape the array to represent 4 weeks of 7 days each and calculate weekly averages
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)
weekly_averages = weekly_temperatures.mean(axis=1)

# Display weekly averages
print("\nWeekly Averages:")
for i, avg in enumerate(weekly_averages, start=1):
    print(f"Week {i}: {avg:.2f}°C")

Daily Temperatures for the Month:
 [17 26 17 24 27 32 19 16 31 28 33 16 24 29 24 35 28 21 31 17 25 22 35 30
 25 28 29 27 23 18]

Weekly Averages:
Week 1: 23.14°C
Week 2: 25.29°C
Week 3: 25.86°C
Week 4: 28.00°C
